name       : haskell-HUnit
version    : 1.3.1.2
release    : 3
source     :
    - http://hackage.haskell.org/package/HUnit-1.3.1.2/HUnit-1.3.1.2.tar.gz : badebf99ae5a4982cdf2f8932f080e349240dc2b75c40e75ce2518ea086c5381
license    : BSD-3-Clause
component  : programming.haskell
summary    : HUnit is a unit testing framework for Haskell, inspired by the JUnit
    tool for Java
description: |
    HUnit is a unit testing framework for Haskell, inspired by the JUnit tool for Java
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
