name       : haskell-HUnit
version    : 1.6.0.0
release    : 6
source     :
    - https://hackage.haskell.org/package/HUnit-1.6.0.0/HUnit-1.6.0.0.tar.gz : 7448e6b966e98e84b7627deba23f71b508e9a61e7bc571d74304a25d30e6d0de
license    : BSD-3-Clause
component  : programming.haskell
summary    : HUnit is a unit testing framework for Haskell, inspired by the JUnit tool for Java
description: |
    HUnit is a unit testing framework for Haskell, inspired by the JUnit tool for Java
builddeps  :
    - haskell-cabal-install
    - haskell-call-stack-devel
rundeps    :
    - devel:
        - haskell-call-stack-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
